# Generated by Django 4.0.5 on 2022-06-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mailings',
            new_name='Mail',
        ),
    ]
