# Generated by Django 4.0.5 on 2022-06-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_rename_mailings_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
