# Generated by Django 4.0.5 on 2022-06-25 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_mail_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
