# Generated by Django 4.0.5 on 2022-06-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_mail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
