# Generated by Django 4.0.5 on 2022-06-26 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0005_emaillist_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
