# Generated by Django 4.0.5 on 2022-06-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
