# Generated by Django 4.0.5 on 2022-06-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.CharField(max_length=20),
        ),
    ]
