# Generated by Django 4.0.5 on 2022-06-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_reservation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
