# Generated by Django 4.0.5 on 2022-06-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(choices=[('1', 'Unsatisfactory'), ('2', 'Needs Improvement'), ('3', 'Met Expectation'), ('4', 'Exceeded Expectation'), ('5', 'Outstanding')], max_length=120)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
