# Generated by Django 4.0.5 on 2022-06-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuItem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.CharField(default='www.url.com', max_length=200),
            preserve_default=False,
        ),
    ]
