# Generated by Django 4.0.5 on 2022-06-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuItem', '0002_remove_menuitem_image_menuitem_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='ff', upload_to=''),
            preserve_default=False,
        ),
    ]
